// Written Perfect Day test, taken on a Detail Apprentice's final training day.
// Every question comes from the Perfect Day rubric or the Miscellaneous
// section. `correct` is the right answer and `wrong` holds the three
// distractors; the app shuffles all four (and the question order) every time
// the test is shown, so the position of the right answer never gives it away.
//
// When the rubric changes, update the matching question here too.

export const TEST_QUESTIONS = [
  // ── Getting Started / Pre-Job ──────────────────────────────────────────────
  { id:"q01", topic:"Getting Started",
    q:"In the night-before text, what do you ask the client to do before you arrive?",
    correct:"Take their personal belongings out of the vehicle",
    wrong:["Leave the vehicle unlocked in the driveway overnight", "Confirm their card on file for payment", "Move the vehicle out of the garage"] },
  { id:"q02", topic:"Pre-Job",
    q:"How early should you plan to arrive at your first job?",
    correct:"10 minutes early", wrong:["5 minutes early","15 minutes early","Right on the scheduled time"] },
  { id:"q03", topic:"Pre-Job",
    q:"Which two things do you check are full (and top off if not) before leaving for the day?",
    correct:"Water tank and generator gas",
    wrong:["Water tank and extractor tank","Generator gas and air compressor tank","Extractor tank and pressure washer oil"] },
  { id:"q04", topic:"Pre-Job",
    q:"How is the On My Way text sent for your first job?",
    correct:"HCP's automated text, timed to the drive from the warehouse",
    wrong:["A personal text from your phone once you're about 10 minutes out", "HCP's automated text, always set to the 15-minute option", "A quick call to the client as you leave the unit"] },

  // ── Arrival ────────────────────────────────────────────────────────────────
  { id:"q05", topic:"Arrival",
    q:"The client doesn't come out for the pre-job inspection. What do you do?",
    correct:"Inspect it yourself and text them any concerns or upsells",
    wrong:["Knock again, then wait for them before starting anything at all", "Skip the inspection and get started on the interior", "Call the office so someone can reach the client first"] },
  { id:"q06", topic:"Arrival",
    q:"You find stains that aren't on the line items. What price range does the upsell script offer?",
    correct:"$25 / $50 / $75", wrong:["$20 / $40 / $60","$30 / $60 / $90","$50 / $75 / $100"] },
  { id:"q07", topic:"Arrival",
    q:"A client pushes back on an upsell. How do you explain the extra charge?",
    correct:"Standard detail cleans it, but fully removing it takes 30–45 more minutes and heavier equipment",
    wrong:["It's company policy for any stain this size, so the price can't be changed or waived for anyone", "If they leave a 5-star review today, you'll take care of it at no charge this time", "Without it the stain sets in permanently and can't be removed on a later visit"] },
  { id:"q08", topic:"Arrival",
    q:"Besides the walkthrough and before pics, what should you go over with the client on arrival?",
    correct:"A time estimate, the vehicle order, when each is needed, and any concerns",
    wrong:["Their payment method, the gate code, and where to park the truck", "Whether they want a recurring plan, a referral card, and a review link", "Which chemicals they prefer, any allergies, and if they want air freshener"] },

  // ── Sequencing & Cleaning ─────────────────────────────────────────────────
  { id:"q09", topic:"Sequencing",
    q:"It's a hot, sunny morning. Which part of the job do you do first?",
    correct:"Exterior first", wrong:["Interior first","Whichever the client asks for","Interior windows, then exterior, then the rest of the interior"] },
  { id:"q10", topic:"Sequencing",
    q:"It's the last job of the day. When do you do the exterior?",
    correct:"Last", wrong:["First","Halfway through the interior","Only if there's time left before dark"] },
  { id:"q11", topic:"Cleaning Sequence",
    q:"What's the correct order to start the interior?",
    correct:"Trash and mats out → air compress → vacuum → clean surfaces",
    wrong:["Air compress → trash and mats out → vacuum → clean surfaces","Trash and mats out → vacuum → air compress → clean surfaces","Vacuum → trash and mats out → clean surfaces → air compress"] },
  { id:"q12", topic:"Cleaning Sequence",
    q:"In what order do you clean the interior seating areas?",
    correct:"Driver seat → back seat driver side → trunk → back seat passenger side → passenger seat",
    wrong:["Driver seat → passenger seat → back seat driver side → back seat passenger side → trunk","Trunk → back seat driver side → back seat passenger side → driver seat → passenger seat","Passenger seat → back seat passenger side → trunk → back seat driver side → driver seat"] },
  { id:"q13", topic:"Cleaning Sequence",
    q:"When can you use LVP instead of a full vacuum?",
    correct:"When the air compressor already cleared most of the debris",
    wrong:["When the vacuum battery or the generator is running low on power", "On leather seats, where the vacuum can scratch", "On any maintenance plan car that was done recently"] },

  // ── Mid-Job / Interior Finish ─────────────────────────────────────────────
  { id:"q14", topic:"Mid-Job",
    q:"What photo goes with the mid-job update text?",
    correct:"A before and after of the dirtiest area",
    wrong:["A photo of the finished exterior","A photo of the job's line items","A before photo of the whole interior"] },
  { id:"q15", topic:"Interior Finish",
    q:"When do you clean the door jambs?",
    correct:"When the exterior is on the job",
    wrong:["On every job, interior-only included","Only when the client asks for it","Only on monthly plan clients"] },

  // ── Exterior ───────────────────────────────────────────────────────────────
  { id:"q16", topic:"Exterior",
    q:"What's the first step of the exterior?",
    correct:"Pre-rinse to mist down and cool the surface",
    wrong:["Spray and scrub the tires and the wheel wells", "Foam the full vehicle starting from the roof", "Apply tar remover to any spots on the paint"] },
  { id:"q17", topic:"Exterior",
    q:"It's hot out. How do you apply foam?",
    correct:"Panel by panel", wrong:["Full car at once, then rinse fast","Only on the lower half of the car","Skip foam and use the wash wands only"] },
  { id:"q18", topic:"Exterior",
    q:"If a wax is needed, when is it applied?",
    correct:"After completing the full exterior",
    wrong:["Right after the pre-rinse","Between foam and the wash wands","Before the tires are scrubbed"] },
  { id:"q19", topic:"Exterior",
    q:"Where do the exterior after pics go?",
    correct:"Attached in HCP", wrong:["Texted to Will","Posted in the team group chat","Saved to your camera roll for the end of the day"] },

  // ── Walkthrough & Close ───────────────────────────────────────────────────
  { id:"q20", topic:"Walkthrough & Close",
    q:"During the final walkthrough, what do you ask the client to do?",
    correct:"Point out anything you missed so you can fix it",
    wrong:["Sign off on the job in HCP before you pack up", "Rate the detail from 1 to 10 so you can log it", "Check the trunk while you finish the exterior"] },
  { id:"q21", topic:"Walkthrough & Close",
    q:"When is the best time to ask for a Google review?",
    correct:"While collecting payment, after the walkthrough",
    wrong:["Right when you arrive and introduce yourself","In the mid-job update text","In the night-before reminder text"] },
  { id:"q22", topic:"Walkthrough & Close",
    q:"How do you send the Google review link when the client is there in person?",
    correct:"AirDrop, with a picture added",
    wrong:["Text it from your personal phone","Write it on the satisfaction card","Email it through HCP after you leave"] },
  { id:"q23", topic:"Walkthrough & Close",
    q:"What does the client get for a referral that books and pays?",
    correct:"$20 off their next service", wrong:["$10 off their next service","$25 store credit","A free add-on of their choice"] },

  // ── Client Not Home / Close-Out / End of Day ──────────────────────────────
  { id:"q24", topic:"Client Not Home",
    q:"The client isn't home when you finish. What do you send them?",
    correct:"A 30-second video walkthrough, the review link, and the referral ask",
    wrong:["Before and after photos of each area with the invoice attached", "A voicemail going over everything that was done on the vehicle", "A text asking them to call when they're home so you can walk them through it"] },
  { id:"q25", topic:"Job Close-Out",
    q:"How many door hangers do you place after each job?",
    correct:"3", wrong:["2","5","10"] },
  { id:"q26", topic:"Job Close-Out",
    q:"After placing the door hangers and satisfaction card, what do you do?",
    correct:"Attach photos of them in HCP",
    wrong:["Text the client a photo of them","Log them on the time sheet","Nothing — just head to the next job"] },
  { id:"q27", topic:"End of Day",
    q:"Which of these is part of your end-of-day routine?",
    correct:"Refill the water tank and empty out the totes and exterior bucket",
    wrong:["Top off the generator gas and restock every chemical bottle in the totes", "Wash and dry the dirty towels at the unit before leaving", "Charge the vacuums and wipe down the seats inside the truck"] },
  { id:"q28", topic:"End of Day",
    q:"Where do dirty towels go at the end of the day?",
    correct:"In the correct dirty bin", wrong:["In the truck to be swapped next morning","In the clean bin if they're only lightly used","Taken home to wash"] },

  // ── Unit, Trucks & Towels ─────────────────────────────────────────────────
  { id:"q29", topic:"The Unit",
    q:"After taking the key out of the key box and unlocking the left black door, what do you do before going inside?",
    correct:"Prop the door open and put the key back in the key box",
    wrong:["Keep the key on you until you leave for the day","Leave the key in the door so the next guy can get in","Hang the key on the hook inside the unit"] },
  { id:"q30", topic:"The Unit",
    q:"When you leave the unit, how do you exit?",
    correct:"Close the garage and exit through the right side garage door",
    wrong:["Close the garage and exit through the left side black door","Leave the garage open for the next truck back","Exit through the main garage door before it closes"] },
  { id:"q31", topic:"The Unit",
    q:"Standing at the entrance of the garage, where does Big Bertha park?",
    correct:"Back left", wrong:["Back right","Front left","The first open spot"] },
  { id:"q32", topic:"The Unit",
    q:"When you get back to the unit, where do you park your Mav?",
    correct:"The next open spot closest to the back",
    wrong:["The same assigned spot every single day", "The open spot closest to the garage door", "Right next to Big Bertha in the back"] },
  { id:"q33", topic:"Towels",
    q:"How many shmuck towels do you take per car?",
    correct:"3", wrong:["1","2","5"] },
  { id:"q34", topic:"Towels",
    q:"How many exterior towels per car in the winter?",
    correct:"3", wrong:["2","4","5"] },
  { id:"q35", topic:"Equipment Care",
    q:"How do you clean the vacuum filter on Wednesdays?",
    correct:"Pop it off and blow it out with the air compressor outside",
    wrong:["Rinse it with the pressure washer and let it air dry in the sun", "Soak it in a bucket of Dawn and warm water overnight", "Tap it against the truck and vacuum the dust off it"] },
  { id:"q36", topic:"Equipment Care",
    q:"When cleaning the extractor, what goes in the 5-gallon bucket that you suck up?",
    correct:"Dawn dish soap and warm water",
    wrong:["Carpet cleaner and hot water","The water line cleaner product","Degreaser and cold water"] },

  // ── Housecall Pro ─────────────────────────────────────────────────────────
  { id:"q37", topic:"Housecall Pro",
    q:"What are the four steps of the HCP job flow you're audited on?",
    correct:"On My Way, Start, Finish, Invoice",
    wrong:["On My Way, Arrive, Start, Finish","Start, Pause, Finish, Invoice","Arrive, Start, Finish, Review"] },
  { id:"q38", topic:"Housecall Pro",
    q:"Why do you need to create a customer before booking a job?",
    correct:"HCP won't schedule a job without a customer",
    wrong:["It's the only way to send them the review link", "So the job counts toward the leaderboard", "So their card can be charged automatically"] },
  { id:"q39", topic:"Housecall Pro",
    q:"What address do you put on a time-off or cover event in HCP?",
    correct:"Wrong Turn Rd Idaho", wrong:["The unit's address","Your home address","Leave the address blank"] },
  { id:"q40", topic:"Housecall Pro",
    q:"You need a day off on a day you're scheduled. What has to happen first?",
    correct:"Find a cover who isn't scheduled that day, and you both add it in HCP",
    wrong:["Text Will so he can find someone to cover your jobs that day", "Add a time-off event in HCP and the schedule moves your jobs to others", "Ask a tech already scheduled that day to take your jobs as well"] },

  // ── Clients ───────────────────────────────────────────────────────────────
  { id:"q41", topic:"Rainy Days",
    q:"It's raining and the client has no cover and the rain won't let up. What do you offer?",
    correct:"Discount the exterior and do the interior only",
    wrong:["Reschedule the full detail for the next dry day","Do the full detail in the rain at full price","Offer a free exterior on their next visit"] },
  { id:"q42", topic:"Rainy Days",
    q:"What's the actual problem with washing a car in the rain?",
    correct:"Drying it", wrong:["The foam won't stick to wet paint","The chemicals get diluted too much","Water spots from the rain itself"] },
  { id:"q43", topic:"Client Questions",
    q:"A client asks about a chemical and you're not sure of the answer. What's the #1 thing to do?",
    correct:"Sound confident, then confirm with Will, Zak, Ethan, or Trevor",
    wrong:["Be honest that you don't know and tell them you'll find out later", "Have them call the office so someone can explain the details", "Read them the label off the bottle so they can see it for themselves"] },
  { id:"q44", topic:"Switchovers",
    q:"What do you earn for switching a one-time client to a Monthly interior + exterior plan?",
    correct:"$50", wrong:["$40","$45","$60"] },
  { id:"q45", topic:"Switchovers",
    q:"What do you earn for switching a one-time client to a Quarterly interior-only plan?",
    correct:"$30", wrong:["$25","$35","$40"] },
  { id:"q46", topic:"Switchovers",
    q:"What's the best tool for selling a recurring plan to a one-time client?",
    correct:"The laminated pamphlet in every vehicle",
    wrong:["Pulling up the website on your phone","Texting them the price list afterward","Writing the prices on the satisfaction card"] },

  // ── Upsells & Add-Ons ─────────────────────────────────────────────────────
  { id:"q47", topic:"Shampoo",
    q:"How long do you let the carpet cleaner dwell before scrubbing?",
    correct:"1–2 minutes", wrong:["10–15 seconds","5 minutes","10 minutes"] },
  { id:"q48", topic:"Shampoo",
    q:"Which drill brush head do you use on carpets and the flat parts of seats?",
    correct:"Flat head", wrong:["Cone head","Either one — they do the same job","Neither — use a toothbrush"] },
  { id:"q49", topic:"Headliner",
    q:"When in the interior do you do a headliner shampoo?",
    correct:"Before anything else on the interior",
    wrong:["After the vacuum, before the surfaces","Last, after the windows","Whenever it fits in the job"] },
  { id:"q50", topic:"Pet Hair",
    q:"What's the order for heavy pet hair removal?",
    correct:"Air compressor → cone head drill brush → pumice stone, vacuuming throughout",
    wrong:["Pumice stone → air compressor → cone head drill brush, then vacuum","Cone head drill brush → pumice stone → air compressor, then vacuum","Vacuum → pumice stone → air compressor → cone head drill brush"] },
  { id:"q51", topic:"Deodorization",
    q:"After spraying deodorizer in the vents, how do you let it work?",
    correct:"AC on full blast with recirculation, doors shut, 5–10 minutes",
    wrong:["Windows cracked with the fan on low for about 5–10 minutes", "Engine off with every door open for about 15 minutes", "AC on fresh-air mode with the doors shut for 1–2 minutes"] },
  { id:"q52", topic:"Wax",
    q:"How often do we recommend a hand wax?",
    correct:"Every 3–4 months", wrong:["Every month","Every 6 months","Once a year"] },
  { id:"q53", topic:"Wax",
    q:"It's sunny out. How much of the vehicle can you wax before wiping it off?",
    correct:"No more than half", wrong:["The whole vehicle","About three-quarters","Just the hood and roof"] },
  { id:"q54", topic:"Wax",
    q:"How do you remove wax?",
    correct:"With the wax rag in circular motions",
    wrong:["With the wax rag in straight lines","With an LVP towel in circular motions","With the wash mitt and a quick rinse"] },
  { id:"q55", topic:"Tar Removal",
    q:"When do you use tar remover?",
    correct:"Before or during the exterior, while the car is wet",
    wrong:["After the exterior is done and the paint is fully dried", "Right after the wax so the remover doesn't strip it", "At the very end of the job, once you're in the shade"] },
];

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
