// Written tests, taken on a Detail Apprentice's final training day: one on the
// Perfect Day rubric and one on the Miscellaneous section (see TESTS below). `correct` is the right answer and `wrong` holds the three
// distractors; the app shuffles all four (and the question order) every time
// the test is shown, so the position of the right answer never gives it away.
//
// `covers` lists the rubric_items each question tests -- every Perfect Day
// item and every Miscellaneous item with instructions should appear at least
// once. When the rubric changes, update or add the matching question here.

export const TEST_QUESTIONS = [
  // ── Getting Started / Pre-Job ──────────────────────────────────────────────
  { id:"q01", test:"perfect_day", covers:["item_01"], topic:"Getting Started",
    q:"In the night-before text, what do you ask the client to do before you arrive?",
    correct:"Take their personal belongings out of the vehicle",
    wrong:["Leave the vehicle unlocked in the driveway overnight", "Confirm their card on file for payment", "Move the vehicle out of the garage"] },
  { id:"q02", test:"perfect_day", covers:["item_09"], topic:"Pre-Job",
    q:"How early should you plan to arrive at your first job?",
    correct:"10 minutes early", wrong:["5 minutes early","15 minutes early","Right on the scheduled time"] },
  { id:"q03", test:"perfect_day", covers:["item_07", "item_08"], topic:"Pre-Job",
    q:"Which two things do you check are full (and top off if not) before leaving for the day?",
    correct:"Water tank and generator gas",
    wrong:["Water tank and extractor tank","Generator gas and air compressor tank","Extractor tank and pressure washer oil"] },
  { id:"q04", test:"perfect_day", covers:["item_10"], topic:"Pre-Job",
    q:"How is the On My Way text sent for your first job?",
    correct:"HCP's automated text, timed to the drive from the warehouse",
    wrong:["A personal text from your phone once you're about 10 minutes out", "HCP's automated text, always set to the 15-minute option", "A quick call to the client as you leave the unit"] },

  // ── Arrival ────────────────────────────────────────────────────────────────
  { id:"q05", test:"perfect_day", covers:["item_11"], topic:"Arrival",
    q:"The client doesn't come out for the pre-job inspection. What do you do?",
    correct:"Inspect it yourself and text them any concerns or upsells",
    wrong:["Knock again, then wait for them before starting anything at all", "Skip the inspection and get started on the interior", "Call the office so someone can reach the client first"] },
  { id:"q06", test:"perfect_day", covers:["item_12", "misc_15"], topic:"Arrival",
    q:"You find stains that aren't on the line items. What price range does the upsell script offer?",
    correct:"$25 / $50 / $75", wrong:["$20 / $40 / $60","$30 / $60 / $90","$50 / $75 / $100"] },
  { id:"q07", test:"perfect_day", covers:["item_12"], topic:"Arrival",
    q:"A client pushes back on an upsell. How do you explain the extra charge?",
    correct:"Standard detail cleans it, but fully removing it takes 30–45 more minutes and heavier equipment",
    wrong:["It's company policy for any stain this size, so the price can't be changed or waived for anyone", "If they leave a 5-star review today, you'll take care of it at no charge this time", "Without it the stain sets in permanently and can't be removed on a later visit"] },
  { id:"q08", test:"perfect_day", covers:["item_56", "item_57"], topic:"Arrival",
    q:"Besides the walkthrough and before pics, what should you go over with the client on arrival?",
    correct:"A time estimate, the vehicle order, when each is needed, and any concerns",
    wrong:["Their payment method, the gate code, and where to park the truck", "Whether they want a recurring plan, a referral card, and a review link", "Which chemicals they prefer, any allergies, and if they want air freshener"] },

  // ── Sequencing & Cleaning ─────────────────────────────────────────────────
  { id:"q09", test:"perfect_day", covers:["item_14"], topic:"Sequencing",
    q:"It's a hot, sunny morning. Which part of the job do you do first?",
    correct:"Exterior first", wrong:["Interior first","Whichever the client asks for","Interior windows, then exterior, then the rest of the interior"] },
  { id:"q10", test:"perfect_day", covers:["item_14"], topic:"Sequencing",
    q:"It's the last job of the day. When do you do the exterior?",
    correct:"Last", wrong:["First","Halfway through the interior","Only if there's time left before dark"] },
  { id:"q11", test:"perfect_day", covers:["item_15", "item_16", "item_17"], topic:"Cleaning Sequence",
    q:"What's the correct order to start the interior?",
    correct:"Trash and mats out → air compress → vacuum → clean surfaces",
    wrong:["Air compress → trash and mats out → vacuum → clean surfaces","Trash and mats out → vacuum → air compress → clean surfaces","Vacuum → trash and mats out → clean surfaces → air compress"] },
  { id:"q12", test:"perfect_day", covers:["item_18"], topic:"Cleaning Sequence",
    q:"In what order do you clean the interior seating areas?",
    correct:"Driver seat → back seat driver side → trunk → back seat passenger side → passenger seat",
    wrong:["Driver seat → passenger seat → back seat driver side → back seat passenger side → trunk","Trunk → back seat driver side → back seat passenger side → driver seat → passenger seat","Passenger seat → back seat passenger side → trunk → back seat driver side → driver seat"] },
  { id:"q13", test:"perfect_day", covers:["item_17"], topic:"Cleaning Sequence",
    q:"When can you use LVP instead of a full vacuum?",
    correct:"When the air compressor already cleared most of the debris",
    wrong:["When the vacuum battery or the generator is running low on power", "On leather seats, where the vacuum can scratch", "On any maintenance plan car that was done recently"] },

  // ── Mid-Job / Interior Finish ─────────────────────────────────────────────
  { id:"q14", test:"perfect_day", covers:["item_19"], topic:"Mid-Job",
    q:"What photo goes with the mid-job update text?",
    correct:"A before and after of the dirtiest area",
    wrong:["A photo of the finished exterior","A photo of the job's line items","A before photo of the whole interior and trunk"] },
  { id:"q15", test:"perfect_day", covers:["item_23"], topic:"Interior Finish",
    q:"When do you clean the door jambs?",
    correct:"When the exterior is on the job",
    wrong:["On every job, interior-only included","Only when the client asks for it","Only on monthly plan clients"] },

  // ── Exterior ───────────────────────────────────────────────────────────────
  { id:"q16", test:"perfect_day", covers:["item_26"], topic:"Exterior",
    q:"What's the first step of the exterior?",
    correct:"Pre-rinse to mist down and cool the surface",
    wrong:["Spray and scrub the tires and the wheel wells", "Foam the full vehicle starting from the roof", "Apply tar remover to any spots on the paint"] },
  { id:"q17", test:"perfect_day", covers:["item_28"], topic:"Exterior",
    q:"It's hot out. How do you apply foam?",
    correct:"Panel by panel", wrong:["Full car at once, then rinse fast","Only on the lower half of the car","Skip foam and use the wash wands only"] },
  { id:"q18", test:"perfect_day", covers:["item_58"], topic:"Exterior",
    q:"If a wax is needed, when is it applied?",
    correct:"After completing the full exterior",
    wrong:["Right after the pre-rinse, before the foam","Between foam and the wash wands","Before the tires are scrubbed"] },
  { id:"q19", test:"perfect_day", covers:["item_35"], topic:"Exterior",
    q:"Where do the exterior after pics go?",
    correct:"Attached in HCP", wrong:["Texted to Will","Posted in the team group chat","Saved to your camera roll for the end of the day"] },

  // ── Walkthrough & Close ───────────────────────────────────────────────────
  { id:"q20", test:"perfect_day", covers:["item_36"], topic:"Walkthrough & Close",
    q:"During the final walkthrough, what do you ask the client to do?",
    correct:"Point out anything you missed so you can fix it",
    wrong:["Have them sign off on the job in HCP before you pack up", "Rate the detail from 1 to 10 so you can log it", "Check the trunk while you finish the exterior"] },
  { id:"q21", test:"perfect_day", covers:["item_38", "misc_13"], topic:"Walkthrough & Close",
    q:"When is the best time to ask for a Google review?",
    correct:"While collecting payment, after the walkthrough",
    wrong:["Right when you arrive and introduce yourself","In the mid-job update text","In the night-before reminder text, with the link"] },
  { id:"q22", test:"perfect_day", covers:["item_38"], topic:"Walkthrough & Close",
    q:"How do you send the Google review link when the client is there in person?",
    correct:"AirDrop, with a picture added",
    wrong:["Text it from your personal phone","Write it on the satisfaction card","Email it through HCP after you leave"] },
  { id:"q23", test:"perfect_day", covers:["item_39"], topic:"Walkthrough & Close",
    q:"What does the client get for a referral that books and pays?",
    correct:"$20 off their next service", wrong:["$10 off their next service","$25 store credit","A free add-on of their choice"] },

  // ── Client Not Home / Close-Out / End of Day ──────────────────────────────
  { id:"q24", test:"perfect_day", covers:["item_40", "item_41", "item_42"], topic:"Client Not Home",
    q:"The client isn't home when you finish. What do you send them?",
    correct:"A 30-second video walkthrough, the review link, and the referral ask",
    wrong:["Before and after photos of each area with the invoice attached", "A voicemail going over everything that was done on the vehicle", "A text asking them to call when they're home so you can walk them through it"] },
  { id:"q25", test:"perfect_day", covers:["item_43"], topic:"Job Close-Out",
    q:"How many door hangers do you place after each job?",
    correct:"3", wrong:["2","5","10"] },
  { id:"q26", test:"perfect_day", covers:["item_45"], topic:"Job Close-Out",
    q:"After placing the door hangers and satisfaction card, what do you do?",
    correct:"Attach photos of them in HCP",
    wrong:["Text the client a photo of them","Log them on the time sheet","Nothing — just head to the next job"] },
  { id:"q27", test:"perfect_day", covers:["item_49", "item_50"], topic:"End of Day",
    q:"Which of these is part of your end-of-day routine?",
    correct:"Refill the water tank and empty out the totes and exterior bucket",
    wrong:["Top off the generator gas and restock every chemical bottle in the totes", "Wash and dry the dirty towels at the unit before leaving", "Charge the vacuums and wipe down the seats inside the truck"] },
  { id:"q28", test:"perfect_day", covers:["item_52"], topic:"End of Day",
    q:"Where do dirty towels go at the end of the day?",
    correct:"In the correct dirty bin", wrong:["In the truck to be swapped next morning","In the clean bin if they're only lightly used","Taken home to wash"] },

  // ── Unit, Trucks & Towels ─────────────────────────────────────────────────
  { id:"q29", test:"misc", covers:["misc_01"], topic:"The Unit",
    q:"After taking the key out of the key box and unlocking the left black door, what do you do before going inside?",
    correct:"Prop the door open and put the key back in the key box",
    wrong:["Keep the key on you until you leave for the day","Leave the key in the door so the next guy can get in","Hang the key on the hook just inside the unit for the next guy"] },
  { id:"q30", test:"misc", covers:["misc_01"], topic:"The Unit",
    q:"When you leave the unit, how do you exit?",
    correct:"Close the garage and exit through the right side garage door",
    wrong:["Close the garage and exit through the left side black door","Leave the garage open for the next truck back","Exit through the main garage door before it closes"] },
  { id:"q31", test:"misc", covers:["misc_02"], topic:"The Unit",
    q:"Standing at the entrance of the garage, where does Big Bertha park?",
    correct:"Back left", wrong:["Back right","Front left","The first open spot"] },
  { id:"q32", test:"misc", covers:["misc_02"], topic:"The Unit",
    q:"When you get back to the unit, where do you park your Mav?",
    correct:"The next open spot closest to the back",
    wrong:["The same assigned spot every single day", "The open spot closest to the garage door", "Right next to Big Bertha in the back"] },
  { id:"q33", test:"misc", covers:["misc_03", "item_06"], topic:"Towels",
    q:"How many shmuck towels do you take per car?",
    correct:"3", wrong:["1","2","5"] },
  { id:"q34", test:"misc", covers:["misc_03", "item_06"], topic:"Towels",
    q:"How many exterior towels per car in the winter?",
    correct:"3", wrong:["2","4","5"] },
  { id:"q35", test:"misc", covers:["misc_04"], topic:"Equipment Care",
    q:"How do you clean the vacuum filter on Wednesdays?",
    correct:"Pop it off and blow it out with the air compressor outside",
    wrong:["Rinse it with the pressure washer and let it air dry in the sun", "Soak it in a bucket of Dawn and warm water overnight", "Tap it against the truck and vacuum the dust off it"] },
  { id:"q36", test:"misc", covers:["misc_05"], topic:"Equipment Care",
    q:"When cleaning the extractor, what goes in the 5-gallon bucket that you suck up?",
    correct:"Dawn dish soap and warm water",
    wrong:["Carpet cleaner and hot water","The water line cleaner product","Degreaser and cold water"] },

  // ── Housecall Pro ─────────────────────────────────────────────────────────
  { id:"q37", test:"misc", covers:["misc_07"], topic:"Housecall Pro",
    q:"What are the four steps of the HCP job flow you're audited on?",
    correct:"On My Way, Start, Finish, Invoice",
    wrong:["On My Way, Arrive, Start, Finish","Start, Pause, Finish, Invoice","Arrive, Start, Finish, Review"] },
  { id:"q38", test:"misc", covers:["misc_08"], topic:"Housecall Pro",
    q:"Why do you need to create a customer before booking a job?",
    correct:"HCP won't schedule a job without a customer",
    wrong:["It's the only way to send them the review link", "So the job counts toward the leaderboard", "So their card can be charged automatically"] },
  { id:"q39", test:"misc", covers:["misc_10"], topic:"Housecall Pro",
    q:"What address do you put on a time-off or cover event in HCP?",
    correct:"Wrong Turn Rd Idaho", wrong:["The unit's address","Your home address","Leave the address blank"] },
  { id:"q40", test:"misc", covers:["misc_10"], topic:"Housecall Pro",
    q:"You need a day off on a day you're scheduled. What has to happen first?",
    correct:"Find a cover who isn't scheduled that day, and you both add it in HCP",
    wrong:["Text Will so he can find someone to cover your jobs that day", "Add a time-off event in HCP and the schedule moves your jobs to others", "Ask a tech already scheduled that day to take your jobs as well"] },

  // ── Clients ───────────────────────────────────────────────────────────────
  { id:"q41", test:"misc", covers:["misc_11"], topic:"Rainy Days",
    q:"It's raining and the client has no cover and the rain won't let up. What do you offer?",
    correct:"Discount the exterior and do the interior only",
    wrong:["Reschedule the full detail for the next dry day","Do the full detail in the rain at full price","Offer a free exterior on their next visit"] },
  { id:"q42", test:"misc", covers:["misc_11"], topic:"Rainy Days",
    q:"What's the actual problem with washing a car in the rain?",
    correct:"Drying it", wrong:["The foam won't stick to wet paint","The chemicals get diluted too much","Water spots from the rain itself"] },
  { id:"q43", test:"misc", covers:["misc_12"], topic:"Client Questions",
    q:"A client asks about a chemical and you're not sure of the answer. What's the #1 thing to do?",
    correct:"Confidently tell them all of our chemicals are eco, pet, and kid friendly, and that we get them from Image FX. If you or the client have more questions, contact the office.",
    wrong:["Be honest that you don't know, tell them you'll look into it, and get back to them after the job is done", "Read them the label off the bottle so they can see the ingredients and safety info for themselves", "Tell them it's the same stuff most car washes use, so there's nothing to worry about with their family or pets"] },
  { id:"q44", test:"misc", covers:["misc_14"], topic:"Switchovers",
    q:"What do you earn for switching a one-time client to a Monthly interior + exterior plan?",
    correct:"$50", wrong:["$40","$45","$60"] },
  { id:"q45", test:"misc", covers:["misc_14"], topic:"Switchovers",
    q:"What do you earn for switching a one-time client to a Quarterly interior-only plan?",
    correct:"$30", wrong:["$25","$35","$40"] },
  { id:"q46", test:"misc", covers:["misc_14"], topic:"Switchovers",
    q:"What's the best tool for selling a recurring plan to a one-time client?",
    correct:"The laminated pamphlet in every vehicle",
    wrong:["Pulling up the website on your phone","Texting them the price list afterward","Writing the prices on the satisfaction card"] },

  // ── Upsells & Add-Ons ─────────────────────────────────────────────────────
  { id:"q47", test:"misc", covers:["misc_16"], topic:"Shampoo",
    q:"How long do you let the carpet cleaner dwell before scrubbing?",
    correct:"1–2 minutes", wrong:["10–15 seconds","5 minutes","10 minutes"] },
  { id:"q48", test:"misc", covers:["misc_16"], topic:"Shampoo",
    q:"Which drill brush head do you use on carpets and the flat parts of seats?",
    correct:"Flat head", wrong:["Cone head","Either one — they do the same job","Neither — use a toothbrush"] },
  { id:"q49", test:"misc", covers:["misc_17"], topic:"Headliner",
    q:"When in the interior do you do a headliner shampoo?",
    correct:"Before anything else on the interior",
    wrong:["After the vacuum, before the surfaces","Last, after the windows","Whenever it fits in the job"] },
  { id:"q50", test:"misc", covers:["misc_18"], topic:"Pet Hair",
    q:"What's the order for heavy pet hair removal?",
    correct:"Air compressor → cone head drill brush → pumice stone, vacuuming throughout",
    wrong:["Pumice stone → air compressor → cone head drill brush, then vacuum","Cone head drill brush → pumice stone → air compressor, then vacuum","Vacuum → pumice stone → air compressor → cone head drill brush"] },
  { id:"q51", test:"misc", covers:["misc_19"], topic:"Deodorization",
    q:"After spraying deodorizer in the vents, how do you let it work?",
    correct:"AC on full blast with recirculation, doors shut, 5–10 minutes",
    wrong:["Windows cracked with the fan on low for about 5–10 minutes", "Engine off with every door open for about 15 minutes", "AC on fresh-air mode with the doors shut for 1–2 minutes"] },
  { id:"q52", test:"misc", covers:["misc_20"], topic:"Wax",
    q:"How often do we recommend a hand wax?",
    correct:"Every 3–4 months", wrong:["Every month","Every 6 months","Once a year"] },
  { id:"q53", test:"misc", covers:["misc_20"], topic:"Wax",
    q:"It's sunny out. How much of the vehicle can you wax before wiping it off?",
    correct:"No more than half", wrong:["The whole vehicle","About three-quarters","Just the hood and roof"] },
  { id:"q54", test:"misc", covers:["misc_20"], topic:"Wax",
    q:"How do you remove wax?",
    correct:"With the wax rag in circular motions",
    wrong:["With the wax rag in straight lines","With an LVP towel in circular motions","With the wash mitt and a quick rinse"] },
  { id:"q55", test:"misc", covers:["misc_21"], topic:"Tar Removal",
    q:"When do you use tar remover?",
    correct:"Before or during the exterior, while the car is wet",
    wrong:["After the exterior is done and the paint is fully dried", "Right after the wax so the remover doesn't strip it", "At the very end of the job, once you're in the shade"] },

  // ── Added so every rubric item is tested ─────────────────────────────────
  { id:"q56", test:"perfect_day", covers:["item_02"], topic:"Getting Started",
    q:"The night before, besides sending the reminder texts, what do you check?",
    correct:"Your route, to confirm the first job's location and when to leave",
    wrong:["The weather for the week, to plan which days you can upsell wax", "Which tech is on the truck next to yours tomorrow", "The leaderboard, to see where your revenue stands"] },
  { id:"q57", test:"perfect_day", covers:["item_03", "item_04", "item_05"], topic:"Pre-Job",
    q:"Which of these is part of your pre-job routine at the unit?",
    correct:"Pre-job checklist done, chemicals topped off, and totes and bucket stocked",
    wrong:["Truck washed, tire pressure checked, and the gas tank filled up all the way", "Each client called to confirm, then the towels loaded up", "Vacuum filters blown out and the extractor tank refilled"] },
  { id:"q58", test:"perfect_day", covers:["item_06"], topic:"Pre-Job",
    q:"How do you decide how many towels go on the truck?",
    correct:"The proper count per car, plus extra for upsells and schedule changes",
    wrong:["One full bag of each towel type, no matter what's on the day's schedule", "Whatever is left in the clean bin that morning", "Exactly enough for the jobs on the schedule, no extras"] },
  { id:"q59", test:"perfect_day", covers:["item_11"], topic:"Arrival",
    q:"When you introduce yourself on arrival, what do you ask the client to do?",
    correct:"Come out so you can do the pre-job inspection together",
    wrong:["Hand you the keys and head back inside", "Move the vehicle into the shade for you", "Show you the nearest outlet and the water spigot to hook up to"] },
  { id:"q60", test:"perfect_day", covers:["item_13"], topic:"Arrival",
    q:"When do you take the before pics?",
    correct:"On arrival, before any cleaning starts",
    wrong:["After the trash and mats are out, so the seats show", "Only when the vehicle is extra dirty", "Right before the mid-job text, so they match"] },
  { id:"q61", test:"perfect_day", covers:["item_20"], topic:"Mid-Job",
    q:"You're running behind and won't make your next job on time. What do you do?",
    correct:"Let the next client know early that you'll be late",
    wrong:["Speed up the rest of this job to make up the time", "Skip the mid-job text to save a few minutes", "Wait and let the On My Way text cover it when you leave"] },
  { id:"q62", test:"perfect_day", covers:["item_21"], topic:"Interior Finish",
    q:"When do the floor mats go back in the vehicle?",
    correct:"Once they're dried, during the interior finish",
    wrong:["Right after you vacuum them", "After the exterior is completely done", "Leave them out on the driveway for the client to put back in"] },
  { id:"q63", test:"perfect_day", covers:["item_22", "item_24", "item_25"], topic:"Interior Finish",
    q:"Before you call the interior done, what do you complete?",
    correct:"Windows cleaned, the interior checklist, and interior after pics",
    wrong:["A mid-job text, a vacuum touch-up, and the door jambs", "The exterior checklist, the tap-to-pay invoice, and the review ask", "A client walkthrough, a video, and the referral ask"] },
  { id:"q64", test:"perfect_day", covers:["item_27"], topic:"Exterior",
    q:"After the pre-rinse, what do you do with the tires?",
    correct:"Spray and scrub them, then rinse them off",
    wrong:["Apply tire shine so it sets while you wash", "Leave them until the very end of the exterior", "Foam them with the body and rinse it all together"] },
  { id:"q65", test:"perfect_day", covers:["item_29", "item_30"], topic:"Exterior",
    q:"After the foam is on, what comes next?",
    correct:"Scrub the full vehicle with the wash wands, then rinse and thoroughly dry",
    wrong:["Let the foam dwell 10 minutes, then rinse and let it air dry", "Rinse it right away, then go over the whole car with dry wash wands", "Wipe the foam off with exterior towels, then give it a rinse"] },
  { id:"q66", test:"perfect_day", covers:["item_31", "item_32"], topic:"Exterior",
    q:"After drying the vehicle, which touch-ups come next?",
    correct:"Windows touched up with the exterior towel, and rims and tire faces dried",
    wrong:["Interior windows redone and the door jambs wiped down a second time", "A second foam pass on the wheels, then a quick rinse", "Wax on the windows and the rims polished with an LVP towel"] },
  { id:"q67", test:"perfect_day", covers:["item_33"], topic:"Exterior",
    q:"What comes right after drying the rims and tire faces?",
    correct:"Tire shine",
    wrong:["The exterior checklist", "Exterior before pics", "A second pre-rinse on the wheels"] },
  { id:"q68", test:"perfect_day", covers:["item_34", "item_35"], topic:"Exterior",
    q:"How do you wrap up the exterior?",
    correct:"Complete the exterior checklist, then attach the after pics in HCP",
    wrong:["Complete the interior checklist and send the client a walkthrough text", "Run the tap-to-pay invoice, then ask for the review", "Send the client a video and mark the job finished"] },
  { id:"q69", test:"perfect_day", covers:["item_37"], topic:"Walkthrough & Close",
    q:"How do you collect payment at the end of the job?",
    correct:"Complete the tap-to-pay invoice",
    wrong:["Let HCP email them the invoice later", "Have them Venmo the company account", "Have them call the office to pay"] },
  { id:"q70", test:"perfect_day", covers:["item_44"], topic:"Job Close-Out",
    q:"Besides the door hangers, what else gets placed after every job?",
    correct:"A customer satisfaction card",
    wrong:["A business card on the dash", "A referral flyer in the cupholder", "An air freshener on the mirror"] },
  { id:"q71", test:"perfect_day", covers:["item_46"], topic:"Job Close-Out",
    q:"What's the last thing you do before driving to the next job?",
    correct:"Send the On My Way text to the next client",
    wrong:["Text the last client a thank-you with their photos", "Call Will with your job times", "Clock your time in the time sheet"] },
  { id:"q72", test:"perfect_day", covers:["item_47", "item_48"], topic:"End of Day",
    q:"At the end of the day, what has to come out of the truck?",
    correct:"All the trash and all your personal belongings",
    wrong:["The vacuums and extractors, to charge overnight", "Just the trash — personal items can stay if the truck is locked", "The chemicals, so they don't freeze"] },
  { id:"q73", test:"perfect_day", covers:["item_51"], topic:"End of Day",
    q:"What do you do with the clean towels you didn't use?",
    correct:"Return them to the correct clean bin",
    wrong:["Leave them in the truck for tomorrow", "Put them in the dirty bin to be safe", "Take them home to keep them dry"] },
  { id:"q74", test:"perfect_day", covers:["item_53", "item_54", "item_55"], topic:"End of Day",
    q:"Before you're done for the day, how do you prep for tomorrow?",
    correct:"Check the schedule, send the night-before texts, confirm the first job's location",
    wrong:["Call each of tomorrow's clients to confirm, then restock the chemicals for the morning", "Text Will your start time and run the truck through a car wash", "Confirm tomorrow's payments in HCP and print out the job sheets"] },
  { id:"q75", test:"misc", covers:["misc_06"], topic:"Housecall Pro",
    q:"Where in HCP do you find a client's address, phone number, job time, and line items?",
    correct:"Their job on your schedule",
    wrong:["The notes on their customer profile", "The invoice once the job is done", "The team's group chat"] },
  { id:"q76", test:"misc", covers:["misc_09"], topic:"Housecall Pro",
    q:"How do you create a new job in HCP?",
    correct:"Schedule page, tap the plus in the top right, choose Job",
    wrong:["Customers page, tap the customer's name, then choose New Invoice", "Tap the plus on the bottom bar and choose Estimate", "Ask Will to put it in from the office"] },
  // ── Added for the separate Miscellaneous test ─────────────────────────────
  { id:"q77", test:"misc", covers:["misc_13"], topic:"Google Reviews",
    q:"When you ask for a Google review, what do you ask the client to mention in it?",
    correct:"Your name", wrong:["The price they paid", "Every service on their invoice", "How long the job took"] },
  { id:"q78", test:"misc", covers:["misc_13"], topic:"Google Reviews",
    q:"How do you get the review link to a client who is standing with you?",
    correct:"AirDrop it to their phone", wrong:["Text it to them that evening", "Write it on the satisfaction card", "Email it from HCP after the invoice"] },
  { id:"q79", test:"misc", covers:["misc_15"], topic:"Upsells",
    q:"In the upsell pitch, what do you tell the client before giving the price?",
    correct:"What you noticed, and that it needs extra time and equipment to get out",
    wrong:["That the detail won't look good unless they add it", "That most of our clients add it on every time", "That the price is only good if they decide right now"] },
  { id:"q80", test:"misc", covers:["misc_17"], topic:"Headliner",
    q:"What's the last step of a headliner shampoo?",
    correct:"Wipe it down with a dry, clean LVP rag", wrong:["Blow it dry with the air compressor", "Spray deodorizer over the whole headliner", "Run the AC on full blast with the doors shut"] },
  { id:"q81", test:"misc", covers:["misc_19"], topic:"Deodorization",
    q:"After you extract a spill spot and spray deodorizer, how do you know the spot is done?",
    correct:"Extract again and smell it, repeating until no smell is left", wrong:["Let it dwell 10 minutes and move on", "Spray it a second time to be safe", "Ask the client to check it at the walkthrough"] },
  { id:"q82", test:"misc", covers:["misc_21"], topic:"Tar Removal",
    q:"What should never happen with tar remover?",
    correct:"Leaving it on the paint without rinsing it off", wrong:["Using it while the car is wet", "Scrubbing small spots with a wash mitt", "Using a shmuck rag on heavy tar"] },
  { id:"q83", test:"misc", covers:["misc_20"], topic:"Wax",
    q:"Where do you look the car over for missed spots or streaks after waxing?",
    correct:"In direct sunlight", wrong:["In the shade so there's no glare", "Inside the client's garage", "Under the truck's work lights"] },
  { id:"q84", test:"misc", covers:["misc_16"], topic:"Shampoo",
    q:"After you steam and extract the seats, how do you help them dry?",
    correct:"Leave the doors open or the windows cracked", wrong:["Wipe them with a wax rag", "Run the heater with the doors shut", "Lay a dry exterior towel over each seat"] },
  { id:"q85", test:"misc", covers:["misc_08"], topic:"Housecall Pro",
    q:"Where do you create a new customer in the HCP app?",
    correct:"Customer page on the bottom bar, plus in the top right, Create New Customer",
    wrong:["Schedule page, plus in the top right, choose Job", "The Invoice page, under New Client", "Settings, then Add Customer"] },
  { id:"q86", test:"misc", covers:["misc_07"], topic:"Housecall Pro",
    q:"Why does Skylo track your HCP job flow on every job?",
    correct:"To track how long jobs take and make sure you get paid", wrong:["So clients can rate you after the job", "To decide who gets the best routes next week", "So HCP can send the client a receipt"] },
  { id:"q87", test:"misc", covers:["misc_05"], topic:"Equipment Care",
    q:"What's the first step of Wednesday extractor cleaning?",
    correct:"Fill it with water and the water line cleaner, then run the pump", wrong:["Suck up a bucket of Dawn and warm water", "Scrub off the vacuum head", "Blow out the hose with the air compressor"] },
  { id:"q88", test:"misc", covers:["misc_10"], topic:"Housecall Pro",
    q:"You agreed to cover Truxton's shift. What time do you set on the HCP event?",
    correct:"8am–5pm", wrong:["Truxton's first job to his last job", "All day, with no times set", "7am–7pm"] },
  { id:"q89", test:"misc", covers:["misc_11"], topic:"Rainy Days",
    q:"A client wants to reschedule for rain, but the weather app shows it letting up in a couple of hours. What do you do?",
    correct:"Reassure them their vehicle will be clean and keep the appointment", wrong:["Reschedule them for the next sunny day", "Offer to do the interior only", "Ask them to call the office to decide"] },
];

// Two written tests, taken separately. Every question has a `test` key.
// The Miscellaneous test leaves out the equipment troubleshooting items.
export const TESTS = {
  perfect_day: { key:"perfect_day", name:"Perfect Day Test",   short:"Perfect Day",   covers:"the Perfect Day rubric" },
  misc:        { key:"misc",        name:"Miscellaneous Test", short:"Miscellaneous", covers:"the Miscellaneous section" },
};
export const TEST_KEYS = Object.keys(TESTS);
export const questionsFor = key => TEST_QUESTIONS.filter(q => q.test === key);

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
