// Shared TECH_MAP — add new hires here once; imported by all four sync functions.
// Key = HCP employee name (exact, case-sensitive). Value = Supabase tech name.
module.exports = {
  "Atticus Andersen":  "Atticus Anderson",
  "Brian Wheelus":     "Brian Wheelus",
  "Britton Dookhran":  "Britton Dookhran",
  "Caleb McDaniel":    "Caleb McDaniel",
  "Cole Burtenshaw":   "Cole Burtenshaw",
  "Ethan Hamilton":    "Ethan Hamilton",
  "Ethan Hansen":      "Ethan Hansen",
  "Jackson Payne":     "Jackson Payne",
  "Jackson Vaughn":    "Jackson Vaughn",
  "JaMuar Hill":       "Jamuar Hill",
  "Jayden Brownlee":   "Jayden Brownlee",
  "Josh Halafuka":     "Josh Halufuka",
  "Kade Andrew":       "Kade Andrew",
  "Kyle Reiff":        "Kyle Rieff",
  "Landon White":      "Landon White",
  "Logan Mannikko":    "Logan Mannikko",
  "Mason Dixon":       "Mason Dixon",
  "Matthew Durkovich": "Matthew Durkovich",
  "Max Hancock":       "Max Hancock",
  "Milos Lewit":       "Milos Lewit",
  "Myles Madarieta":   "Myles Madarieta",
  "Riley Lyon":        "Riley Lyon",
  "Riley Wooden":      "Riley Wooden",
  "Tom Lorenc":        "Tom Lorenc",
  "Trevor Prince":     "Trevor Prince",
  "Will Faulkner":     "Will Faulkner",
  "Zak Lundblade":     "Zak Lundblade",
};
